package com.grupo3aor.innovationlab.service;

import com.grupo3aor.innovationlab.dto.PhysiologicalReadingDTO;
import com.opencsv.CSVReader;
import org.springframework.stereotype.Service;
import org.springframework.web.multipart.MultipartFile;
import com.grupo3aor.innovationlab.repository.SimulationRepository;
import com.grupo3aor.innovationlab.domain.entity.Simulation;

import java.io.InputStreamReader;
import java.io.Reader;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * Service responsible for parsing CSV files generated by BioGears.
 * Converts raw physiological data into standard DTOs.
 */
@Service
public class BioGearsParserService {

    private final SimulationRepository simulationRepository;
    private final GlobalSettingsService globalSettingsService;

    public BioGearsParserService(SimulationRepository simulationRepository, GlobalSettingsService globalSettingsService) {
        this.simulationRepository = simulationRepository;
        this.globalSettingsService = globalSettingsService;
    }

    /**
     * Parses a multipart CSV file and returns a list of physiological readings.
     *
     * @param file         the uploaded CSV file
     * @param simulationId the identifier of the simulation
     * @return a list of physiological reading DTOs
     * @throws Exception if parsing fails
     */
    public List<PhysiologicalReadingDTO> parseCsv(MultipartFile file, UUID simulationId) throws Exception {
        if (globalSettingsService.isDbFailed()) {
            throw new org.springframework.web.server.ResponseStatusException(
                org.springframework.http.HttpStatus.SERVICE_UNAVAILABLE,
                "Sistema em Modo Degradado. Uploads em lote temporariamente indisponíveis");
        }
        
        List<PhysiologicalReadingDTO> readings = new ArrayList<>();
        
        try (Reader reader = new InputStreamReader(file.getInputStream());
             CSVReader csvReader = new CSVReader(reader)) {
             
            String[] header = csvReader.readNext();
            if (header == null) {
                throw new IllegalArgumentException("CSV file is empty");
            }
            
            // Dynamically map BioGears columns to indexes
            int timeIdx = -1, hrIdx = -1, spo2Idx = -1, sbpIdx = -1, tempIdx = -1, rrIdx = -1, tidalIdx = -1, phIdx = -1;
            for (int i = 0; i < header.length; i++) {
                String col = header[i].trim();
                if (col.startsWith("Time")) timeIdx = i;
                else if (col.startsWith("HeartRate")) hrIdx = i;
                else if (col.startsWith("OxygenSaturation")) spo2Idx = i;
                else if (col.startsWith("SystolicArterialPressure")) sbpIdx = i;
                else if (col.startsWith("CoreTemperature")) tempIdx = i;
                else if (col.startsWith("RespirationRate")) rrIdx = i;
                else if (col.startsWith("TidalVolume")) tidalIdx = i;
                else if (col.startsWith("ArterialBloodPH")) phIdx = i;
            }
            
            if (timeIdx == -1) throw new IllegalArgumentException("CSV missing 'Time(s)' column");

            String[] row;
            Simulation sim = simulationRepository.findById(simulationId)
                .orElseThrow(() -> new IllegalArgumentException("Simulation not found"));
            LocalDateTime baseTime = sim.getStartedAt();
            if (baseTime == null) baseTime = LocalDateTime.now(); // Fallback if missing
            
            while ((row = csvReader.readNext()) != null) {
                if (row.length <= timeIdx || row[timeIdx].isEmpty()) continue;
                
                double timeSeconds = Double.parseDouble(row[timeIdx]);
                // To ensure historical playback flows correctly, we add the elapsed seconds to the base time
                LocalDateTime timestamp = baseTime.plusNanos((long) (timeSeconds * 1_000_000_000L));

                // Parse and generate Heart Rate DTO
                if (hrIdx != -1 && hrIdx < row.length && !row[hrIdx].isEmpty()) {
                    readings.add(createDTO(simulationId, "HR", "1/min", row[hrIdx], timestamp, 1.0));
                }
                
                // Parse SpO2 (BioGears outputs fraction like 0.98, we multiply by 100 for percentage)
                if (spo2Idx != -1 && spo2Idx < row.length && !row[spo2Idx].isEmpty()) {
                    readings.add(createDTO(simulationId, "SpO2", "%", row[spo2Idx], timestamp, 100.0));
                }
                
                // Parse Systolic Blood Pressure
                if (sbpIdx != -1 && sbpIdx < row.length && !row[sbpIdx].isEmpty()) {
                    readings.add(createDTO(simulationId, "SBP", "mmHg", row[sbpIdx], timestamp, 1.0));
                }

                // Parse Core Temperature
                if (tempIdx != -1 && tempIdx < row.length && !row[tempIdx].isEmpty()) {
                    readings.add(createDTO(simulationId, "TEMP", "C", row[tempIdx], timestamp, 1.0));
                }

                // Parse Respiration Rate
                if (rrIdx != -1 && rrIdx < row.length && !row[rrIdx].isEmpty()) {
                    readings.add(createDTO(simulationId, "RR", "1/min", row[rrIdx], timestamp, 1.0));
                }

                // Parse Tidal Volume
                if (tidalIdx != -1 && tidalIdx < row.length && !row[tidalIdx].isEmpty()) {
                    readings.add(createDTO(simulationId, "TidalVolume", "mL", row[tidalIdx], timestamp, 1.0));
                }

                // Parse Arterial Blood PH
                if (phIdx != -1 && phIdx < row.length && !row[phIdx].isEmpty()) {
                    readings.add(createDTO(simulationId, "ArterialBloodPH", "pH", row[phIdx], timestamp, 1.0));
                }
            }
        }
        
        return readings;
    }
    
    private PhysiologicalReadingDTO createDTO(UUID simulationId, String handle, String unit, String rawValue, LocalDateTime timestamp, double multiplier) {
        PhysiologicalReadingDTO dto = new PhysiologicalReadingDTO();
        dto.setSimulationId(simulationId);
        dto.setHandle(handle);
        dto.setUnit(unit);
        dto.setTimestamp(timestamp);
        
        Double value = Double.parseDouble(rawValue) * multiplier;
        // Round to 2 decimal places to keep charts clean
        dto.setValue(Math.round(value * 100.0) / 100.0);
        return dto;
    }
}
